"""empty message

Revision ID: 68ba135a2526
Revises: 887a0e2f45d9
Create Date: 2024-06-09 14:30:27.514741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ba135a2526'
down_revision = '887a0e2f45d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom_complet', sa.String(), nullable=False))
        batch_op.drop_column('prenoms')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('prenoms', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('nom_complet')

    # ### end Alembic commands ###
