"""empty message

Revision ID: 6f99212e22d0
Revises: 
Create Date: 2024-06-09 10:46:25.524208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f99212e22d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_column('nb_Participant')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_epreuve', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('Epreuve_ID_FK', 'epreuve', ['id_epreuve'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint('Epreuve_ID_FK', type_='foreignkey')
        batch_op.drop_column('id_epreuve')

    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_Participant', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
