"""empty message

Revision ID: 861b51714a43
Revises: 
Create Date: 2024-06-07 01:39:41.914638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861b51714a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_id'), ['id'], unique=False)

    with op.batch_alter_table('epreuve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epreuve_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epreuve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epreuve_id'))

    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_id'))

    # ### end Alembic commands ###
