"""empty message

Revision ID: 887a0e2f45d9
Revises: 2bf943cb33ac
Create Date: 2024-06-09 12:04:23.126531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887a0e2f45d9'
down_revision = '2bf943cb33ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cavalier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(), nullable=False))
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    with op.batch_alter_table('epreuve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lieu', sa.String(), nullable=False))

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_photo', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('heure_photo', sa.Time(), nullable=False))
        batch_op.create_foreign_key('Cavalier_ID_FK', 'cavalier', ['id_cavalier'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint('Cavalier_ID_FK', type_='foreignkey')
        batch_op.drop_column('heure_photo')
        batch_op.drop_column('date_photo')

    with op.batch_alter_table('epreuve', schema=None) as batch_op:
        batch_op.drop_column('lieu')

    with op.batch_alter_table('cavalier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
